# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r3vShojV06zVcWInyVSb5XyXL0L_f5VF
"""

!pip install git+https://github.com/huggingface/diffusers
!pip install transformers accelerate safetensors

from diffusers import StableDiffusionXLPipeline
import torch
from transformers.pipelines.image_to_text import Image
from IPython.display import display

pipe= StableDiffusionXLPipeline.from_pretrained(
    "segmind/SSD-1B",
    torch_dtype = torch.float16,
    use_safetensors= True,
    variant = "fp16"
)

pipe.to("cuda")

prompt = "An astronaut riding a green horse"
neg_prompt = "ugly, blurry , poor quality"

image = pipe(prompt=prompt , negative_prompt = neg_prompt).images[0]

display(image)

